import { type NextPage } from "next";
import Head from "next/head";
import Image, { type StaticImageData } from "next/image";
import bg from "../../public/images/home/bg.png";
import mobile from "../../public/images/home/mobile.jpg";
import kite from "../../public/images/home/kite.jpg";
import wetsuit from "../../public/images/home/wetsuit.jpg";
import board from "../../public/images/home/board.jpg";
import { Button, Container } from "../components/index";
import Navbar from "~/components/Navbar";
import { motion, useScroll, useTransform } from "framer-motion";
import { useRef } from "react";

const Home: NextPage = () => {
  const ref = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ["end end", "end start"],
  });

  const scale = useTransform(scrollYProgress, [0, 1], [1, 0.7]);
  const opacity = useTransform(scrollYProgress, [0, 0.45], [1, 0]);

  const imageScale = useTransform(scrollYProgress, [0, 1], [1, 1.2]);
  const gradientOpacity = useTransform(scrollYProgress, [0, 0.45], [0.4, 0]);
  const mobileScreenOpacity = useTransform(
    scrollYProgress,
    [0, 0.45],
    [0.4, 0]
  );

  return (
    <>
      <Head>
        <title>Airborne</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" relative  h-screen w-screen">
        <Navbar />

        <div ref={ref} className="fixed">
          <motion.div
            style={{ opacity: mobileScreenOpacity, scale: imageScale }}
            className="fixed top-0 z-10  h-screen  w-screen bg-black  md:hidden"
          ></motion.div>
          <motion.div
            style={{ opacity: gradientOpacity, scale: imageScale }}
            className="fixed top-0 z-10  h-screen  w-screen bg-gradient-to-br from-black to-transparent opacity-70"
          ></motion.div>

          <motion.div style={{ scale: imageScale, opacity }}>
            <Image
              src={bg}
              alt="kiteboarder jumping"
              className="z-0 hidden  h-screen w-screen object-cover md:block"
            ></Image>
            <Image
              src={mobile}
              alt="kiteboarder jumping"
              className="z-0 block  h-screen w-screen object-cover md:hidden"
            ></Image>
          </motion.div>
          <Container maxWidth="7xl" className=" relative z-20 m-auto">
            <motion.div
              style={{ scale, opacity }}
              className="absolute bottom-0 z-20 flex flex-col gap-4  pb-24 pr-4 text-center md:gap-6 md:pb-16 md:pr-0  md:text-left"
            >
              <h1 className="max max-w-xl text-5xl font-bold md:text-7xl">
                Take Your Kitesurfing to New Heights
              </h1>
              <p className="max md:text-md z-0 max-w-lg text-lg font-light">
                Airborne Kiteboarding offers a wide range of kitesurfing gear
                for all levels of riders, from beginner packages to
                high-performance gear.
              </p>
              <Button
                color="primary"
                padding="wide"
                className=" mx-auto self-start md:mx-0"
              >
                SHOP NOW
              </Button>
            </motion.div>
          </Container>
        </div>
      </main>

      <div className=" w-full ">
        <KitesSection />
      </div>
    </>
  );
};

export default Home;

// function KitesSection() {
//   return (
//     <div className="relative h-screen w-screen">
//       <div className="absolute top-0 z-10 h-screen w-screen bg-gray-900 opacity-50" />
//       <Image
//         src={kite}
//         alt="kite"
//         className=" h-screen w-screen object-cover saturate-50"
//       ></Image>
//     </div>
//   );
// }

// function KitesSection() {
//   const ref = useRef<HTMLDivElement>(null);
//   const { scrollYProgress } = useScroll({
//     target: ref,
//     offset: ["start end", "start start"],
//   });

//   const scale = useTransform(scrollYProgress, [0, 0.9], [0.8, 1]);

//   return (
//     <section className="relative h-[200vh]  w-screen">
//       <div ref={ref} className="sticky top-16">
//         <Container maxWidth="none" className=" m-auto ">
//           <motion.div
//             style={{ scale }}
//             className="w-fulll relative h-[calc(100vh-84px)] overflow-hidden rounded-xl bg-gray-900"
//           >
//             {/* <div className="absolute top-0 z-10 h-screen w-full bg-gray-900 opacity-50" />
//             <Image
//               src={kite}
//               alt="kite"
//               className=" z-0 h-[calc(100vh-84px)] w-full object-cover saturate-50"
//             /> */}
//           </motion.div>
//         </Container>
//       </div>
//     </section>
//   );
// }

// function KitesSection() {
//   const ref = useRef<HTMLDivElement>(null);
//   const { scrollYProgress } = useScroll({
//     target: ref,
//     offset: ["start end", "start start"],
//   });

//   const scale = useTransform(scrollYProgress, [0, 0.9], [1, 1]);
//   const borderRadius = useTransform(scrollYProgress, [0, 0.9], [20, 0]);

//   return (
//     <section className="relative h-[250vh] w-screen">
//       <div ref={ref} className="sticky top-16">
//         <motion.div
//           style={{ scale }}
//           className="w-fulll relative h-[calc(100vh-84px)] overflow-hidden rounded-xl bg-gray-900"
//         >
//           <Container maxWidth="none" className=" m-auto ">
//             <div className=" flex  flex-col items-center py-8 text-center">
//               <h2 className=" w-max pb-4 text-4xl font-medium">
//                 Discover our <span className=" font-bold"> Products</span>
//               </h2>
//               <p className="max-w-2xl">
//                 Lorem ipsum dolor sit amet consectetur adipisicing elit.
//                 Quisquam quod, voluptate, quia, voluptatum quas voluptates
//                 quibusdam voluptatibus quae quidem quos nemo. Quisquam, quae.
//                 Quisquam, quae. Quisquam, quae. Quisquam, quae. Quisquam, quae.
//                 Quisquam, quae.
//               </p>
//             </div>
//           </Container>
//         </motion.div>
//       </div>
//     </section>
//   );
// }

function KitesSection() {
  const ref = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ["start end", "end end"],
  });

  const scale = useTransform(scrollYProgress, [0, 0.9], [0.8, 1]);
  const borderRadius = useTransform(scrollYProgress, [0, 0.9], [20, 0]);
  const textOpacity = useTransform(scrollYProgress, [0, 0.2], [0, 1]);

  return (
    <motion.div
      style={{ borderRadius }}
      ref={ref}
      className="relative min-h-screen  "
    >
      <Container
        maxWidth="8xl"
        className=" m-auto flex min-h-screen flex-col items-center justify-center"
      >
        <motion.div
          style={{ scale, opacity: textOpacity }}
          className=" flex flex-col items-center justify-center py-12"
        >
          <h2 className=" pb-4 text-center text-4xl font-medium">
            Discover our <span className=" font-bold"> Products</span>
          </h2>
          <p className="max-w-2xl text-center">
            Check the new 2023 range of kites, boards and wetsuits.
          </p>
        </motion.div>
        <div className=" mb-12 grid w-full grid-cols-1 gap-6 ">
          <GridElement key="1" image={kite}>
            <h3 className=" text-2xl font-semibold">Kites</h3>
            <p className="max-w-md">
              Fly high with the new range of kites. Choose from a wide range of
              shapes and sizes.
            </p>
            <Button color="secondary">Shop Now</Button>
          </GridElement>
          <GridElement key="2" image={wetsuit}>
            <h3 className=" text-2xl font-semibold">Wetsuits</h3>
            <p className="max-w-md">
              Stay warm and dry with our range of wetsuits. Choose from a wide
              range of shapes and sizes.
            </p>
            <Button color="secondary">Shop Now</Button>
          </GridElement>
          <GridElement key="3" image={board}>
            <h3 className=" text-2xl font-semibold">Boards</h3>
            <p className="max-w-md">
              Reach new speeds with our range of boards. Choose from a wide
              range of shapes and sizes.
            </p>
            <Button color="secondary">Shop Now</Button>
          </GridElement>
        </div>
      </Container>
    </motion.div>
  );
}

function GridElement({
  children,
  image,
}: {
  children?: React.ReactNode;
  image: StaticImageData;
}) {
  const ref = useRef<HTMLDivElement>(null);
  const { scrollYProgress } = useScroll({
    target: ref,
    offset: ["start end", "center center"],
  });

  const scale = useTransform(scrollYProgress, [0, 0.9], [0.7, 1]);
  const bgOpacity = useTransform(scrollYProgress, [0, 0.9], [0, 0.7]);
  const textOpacity = useTransform(scrollYProgress, [0, 0.5, 0.9], [0, 0, 1]);

  return (
    <motion.div
      style={{ scale }}
      ref={ref}
      className="relative h-[70vh] overflow-hidden rounded-xl bg-gray-800 "
    >
      <motion.div
        style={{ opacity: bgOpacity }}
        className=" absolute top-0 z-10 h-full w-full bg-gray-950 opacity-50"
      />
      <Image src={image} alt="kite" className=" h-full  object-cover" />
      <motion.div
        style={{ opacity: textOpacity }}
        className="absolute top-0 z-10 flex h-full w-full flex-col items-center justify-center gap-4 p-4 text-center "
      >
        {children}
      </motion.div>
    </motion.div>
  );
}

// h-[calc(100vh-64px)]
