import { type NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import bg from "../../public/images/home/bg.png";
import { Button, Container } from "../components/index";
import Navbar from "~/components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Airborne</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" relative z-0 h-screen w-screen">
        <div className=" absolute z-0 h-screen  w-screen bg-gradient-to-br from-black to-transparent opacity-60"></div>
        <Navbar />

        <Image
          src={bg}
          alt="kiteboarder jumping"
          className="h-screen  w-screen object-cover"
        ></Image>
        <Container maxWidth="7xl" className="z-0 m-auto">
          <div className="absolute bottom-0 z-0 flex flex-col gap-6 pb-16">
            <h1 className="max max-w-xl text-7xl font-bold">
              Take Your Kitesurfing to New Heights
            </h1>
            <p className="max text-md z-0 max-w-lg font-light">
              Airborne Kiteboarding offers a wide range of kitesurfing gear for
              all levels of riders, from beginner packages to high-performance
              gear.
            </p>
            <Button color="primary" padding="wide" className=" self-start">
              SHOP NOW
            </Button>
          </div>
        </Container>
      </main>
      <div className="h-screen"></div>
    </>
  );
};

export default Home;
